$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: deployment
endpoint_name: endpoint
model: azureml:diabetes-model-prod:1
instance_type: Standard_DS2_v2
instance_count: 1